# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[8.62710073e-01 4.64768773e-04 1.15669434e-01]
  [3.42995103e-01 4.38303155e-01 6.67572141e-01]
  [1.92543909e-01 6.67051300e-01 5.40818057e-01]]

 [[9.36392059e-01 6.05702461e-01 5.13947297e-01]
  [8.16042702e-01 1.70069329e-01 4.89458009e-02]
  [4.45554270e-03 9.59611595e-01 2.07320136e-01]]

 [[4.13003783e-01 5.36905723e-01 8.31052055e-01]
  [4.11487930e-01 8.21795811e-01 4.03547093e-01]
  [6.74512033e-01 5.14366688e-02 6.90579496e-01]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
import numpy as np
x = np.diag([1,2,3,4,5])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [14]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [18]:
x= np.random.random((5,5))
print("Original Array:")
print('\n')
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print('\n')
print("After normalization:")
print("\n")
print(x)

Original Array:


[[0.23062978 0.20511223 0.34725487 0.54924845 0.54275885]
 [0.80997108 0.67676173 0.79371509 0.45502657 0.40205068]
 [0.20313601 0.45923799 0.26116315 0.43210352 0.22125931]
 [0.59348098 0.67947834 0.00821193 0.97952302 0.22668643]
 [0.37626756 0.38327998 0.95009716 0.84231744 0.01190101]]


After normalization:


[[0.22898724 0.202716   0.349057   0.55701672 0.55033544]
 [0.82544013 0.68829627 0.80870399 0.46001188 0.40547128]
 [0.20068141 0.46434769 0.26042246 0.43641177 0.21934   ]
 [0.60255572 0.69109312 0.         1.         0.22492742]
 [0.37892662 0.38614616 0.969705   0.85874188 0.00379804]]


# 5.  How to find common values between two arrays?

In [19]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [20]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [21]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 1 1 1 1]
Second array:
[1 1 0 1 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [24]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.63689262 0.57137721 0.21895689 0.85997962 0.02571439 0.38599827
 0.4872949  0.07593981 0.14091254 0.68362936]
Maximum value replaced by 0:
[0.63689262 0.57137721 0.21895689 0.         0.02571439 0.38599827
 0.4872949  0.07593981 0.14091254 0.68362936]


# 9. How to print all the values of an array?

In [28]:
n = np.arange(1,21).reshape(5,4)
print(n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


# 10.Subtract the mean of each row of a matrix

In [29]:
X = np.random.rand(5,5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.97049212 0.57023382 0.380028   0.37742906 0.13840408]
 [0.26731136 0.32468527 0.67032638 0.10832895 0.6087704 ]
 [0.26653021 0.16351532 0.61237353 0.84139148 0.37304889]
 [0.55414445 0.83757817 0.18732321 0.73752125 0.80246185]
 [0.64983538 0.28557223 0.3644467  0.36189353 0.85361469]]

Subtract the mean of each row of the said matrix:

[[ 0.48317471  0.08291641 -0.10728941 -0.10988836 -0.34891334]
 [-0.12857311 -0.0711992   0.27444191 -0.28755552  0.21288593]
 [-0.18484167 -0.28785657  0.16100164  0.39001959 -0.078323  ]
 [-0.06966134  0.21377238 -0.43648257  0.11371546  0.17865607]
 [ 0.14676287 -0.21750027 -0.13862581 -0.14117898  0.35054218]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [35]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,10).reshape(3,3)
z = np.dot(x,y)
print("Dot Product is")
print(z)
print("\n")
print(f"Diagonal is {np.diag(z)}")

Dot Product is
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Diagonal is [ 30  81 150]


# 13.How to find the most frequent value in an array?

In [40]:
x = np.random.randint(0, 10, 25)
print(x)
print(f"Most frequent value is : { np.bincount(x).argmax()}")

[5 2 6 5 6 7 4 0 1 3 7 4 6 5 0 0 3 4 8 9 6 9 3 4 7]
Most frequent value is : 4


# 14.How to get the n largest values of an array

In [43]:
x = np.random.randint(1,20,10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 8  6 13  1  4 14 19 16 18  6]
[19]


# 15.How to create a record array from a regular array?

In [44]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
